### ISSUE TITLE
Add Buses Locations Overlay onto Map

### ISSUE THREAD

**Issue by kreulenk** [nhazelton/GTNav#3]

**Comment by nhazelton** [comment]
Adding issue template to satiate formatting:

Task Details:
- It is now time to implement the functionality that will allow us to display routes and bus icons on the Google Map fragment. Whether this is done by creating a separate view to lay over the main activity or creating a different instance of the Google Map remains to be seen, but for now it is necessary to create the view that will eventually become the overlay. The logic that places buses need not be fully implemented at this time, but such work should be far enough to where icons can be placed on the map at will.

Acceptance Scenarios:
- GIVEN the user is viewing the main activity, WHEN location services and GPS are enabled, THEN the GoogleMap should display route maps and substituted bus locations.

Done Done Criteria:
- This issue can be safely closed when it is possible to display the map alongside some combination of route lines and bus markers. The functionality that will place these markers accurately will be implemented at a later time.
