### ISSUE TITLE
Create Basic UI Elements

### ISSUE THREAD

**Issue by nhazelton** [nhazelton/GTNav#9]
Task Details:
- Add a search bar near the top of the MainActivity
- Ensure the GoogleMap displays properly underneath the new UI elements, either as a window in the center of the screen or as an underlay
- Add color-coded buttons, each appropriately labeled "Walk" and "Ride"

Acceptance Scenarios:
- GIVEN a user is viewing the main activity, WHEN the search bar UI element is tapped, THEN a keyboard and mutable text field should display
- GIVEN a user is viewing the main activity, WHEN the Google Map is manipulated, THEN the map should response appropriately without interference to the other UI elements
- GIVEN a user is viewing the main activity, WHEN either of the route type buttons are tapped, THEN the buttons should response appropriately indicating that they have been tapped

Done Done Criteria:
- Issue can be safely closed when the search bar, map, and route selection elements are all present on the main activity view and can be interacted upon without interference to other elements. <strong>The intended future functionality of the search bar and buttons need not be implemented at this time.</strong>

**Comment by kreulenk** [comment]
I can add the search bar and will attempt to add the locations of different GT landmarks throughout campus
